#!/bin/bash

. "$(git --exec-path)/git-sh-setup"

function run() {
    find . -name .git | while read -r dot_git; do 
        REPO=$(dirname "${dot_git}")
        cd "${REPO}" || die "can't access ${REPO}"
        echo "➔ ${REPO}"
        echo "running: $*"
        $*
    done
}

case $1 in
    pull)
        echo "git pull"
        run git pull
    ;;
    stash)
        echo "git stash"
    ;;
    *)
        echo "cmd: $*"
    ;;
esac



